esphome:
  name: Basic_Fan

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: "Network Name"
  password: "Network Password"

logger:

api:

ota:
  platform: esphome


web_server:

output:
  - platform: ledc
    pin: 5
    id: fan_pwm_out
    frequency: 25000 Hz

fan:
  - platform: speed
    output: fan_pwm_out
    name: "P1P Exhaust Fan"
    id: exhaust_fan

sensor:
  - platform: pulse_counter
    pin: 4
    name: "P1P Exhaust RPM"
    id: exhaust_rpm
    update_interval: 1s
    internal_filter: 10us
    filters:
      - multiply: 30   # (Hz * 60) / 2 pulses = RPM

